import React from 'react'
import Input from "../../../UI/Input";
import NewModal from "../../../UI/Modal";
import { Row, Col } from "react-bootstrap";

// render update categories modal
const UpdateCategoriesModal = (props) => {

  const {
      size, 
      handleClose,
      onSubmit,
      modalTitle,
      show,
      expandedArray,
      checkedArray,
      handleCategoryInput,
      categoryList // generated by createCategoryList function
  } = props

  // console.log(checkedArray)

  return (
    <NewModal
      modalTitle={modalTitle}
      show={show}
      onSubmit={onSubmit}
      handleClose={handleClose}
      size={size}
    >
      <Row>
        <Col>
          <h6>Expanded Categories</h6>
        </Col>
      </Row>
      {expandedArray.length > 0 &&
        expandedArray.map((item, index) => (
          <Row key={index}>
            <Col>
              <Input
                placeholder={item.name}
                value={item.name}
                onChange={(e) =>
                  handleCategoryInput("name", e.target.value, index, "expanded")
                }
              />
            </Col>
            <Col>
              <select
                className="form-control"
                value={item.parentId}
                onChange={(e) =>
                  handleCategoryInput(
                    "parentId",
                    e.target.value,
                    index,
                    "expanded"
                  )
                }
              >
                <option>select category</option>
                {categoryList.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.name}
                  </option>
                ))}
              </select>
            </Col>
            <Col>
              <select 
                className="form-control"
                value={item.type}
                onChange={(e) => handleCategoryInput("type", e.target.value, index, "expanded")}
              >
                <option value="">Select Type</option>
                <option value="store">Store</option>
                <option value="product">Product</option>
                <option value="page">Page</option>
              </select>
            </Col>
          </Row>
        ))}

      <Row>
        <Col>
          <h6>Checked Categories</h6>
        </Col>
      </Row>
      {checkedArray.length > 0 &&
        checkedArray.map((item, index) => (
          <Row key={index}>
            <Col>
              <Input
                placeholder={item.name}
                value={item.name}
                onChange={(e) =>
                  handleCategoryInput("name", e.target.value, index, "checked")
                }
              />
            </Col>
            <Col>
              <select
                className="form-control"
                value={item.parentId}
                onChange={(e) =>
                  handleCategoryInput(
                    "parentId",
                    e.target.value,
                    index,
                    "checked"
                  )
                }
              >
                <option>select category</option>
                {categoryList.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.name}
                  </option>
                ))}
              </select>
            </Col>
            <Col>
              <select 
                className="form-control"
                value={item.type}
                onChange={(e) => handleCategoryInput("type", e.target.value, index, "checked")}
              >
                <option value="">Select Type</option>
                <option value="store">Store</option>
                <option value="product">Product</option>
                <option value="page">Page</option>
              </select>
            </Col>
          </Row>
        ))}
    </NewModal>
  );
};

export default UpdateCategoriesModal;